优化 pre-commit

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,97 +1,43 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
-function askContinue() {
-    read -p "Errors found, input [y/yes] to continue to commit:" content
-    if [[ ${content} == "y" || ${content} == "yes" ]] ;then
-        echo "Errors found, but continue to commit"
-        exit 0
-    fi
-    echo "Abort to commit ~"
-    exit 1
-}
+PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
+STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`
 
-# 引入配置文件
-# read config file
-source ./vendor/webergiles/php-csc/phpcsc.ini
-
-# 检查phplint的命令路径是否配置
-# 如果没有配置,则使用默认的路径
-# 如果配置了,则进一步检查配置的路径是否正确
-# check if phplint_path is config
-if [[ x"$phplint_path" = x ]]; then
-    phplint_path="./vendor/bin/phplint"
-else
-    ${phplint_path} --version > /dev/null
-    if [[ $? -ne 0 ]]; then
-        echo "Command phplint error, please check it and retry~"
-        exit 1
-    fi
+# Determine if a file list is passed
+if [ "$#" -eq 1 ]
+then
+    oIFS=$IFS
+    IFS='
+    '
+    SFILES="$1"
+    IFS=$oIFS
 fi
+SFILES=${SFILES:-$STAGED_FILES_CMD}
 
-# 检查phpcs的命令路径是否配置
-# 如果没有配置,则使用默认的路径
-# 如果配置了,则进一步检查配置的路径是否正确
-# check if phpcs_path is config
-if [[ x"$phpcs_path" = x ]]; then
-    phpcs_path="phpcs"
-else
-    ${phpcs_path} --version > /dev/null
-    if [[ $? -ne 0 ]]; then
-        echo "Command phpcs error, please check it and retry~"
-        exit 1
-    fi
-fi
-
-# 获取本次提交的差异文件
-a=`git status -s`
-
-array=(${a//,/ })
-for var in ${array[@]}
+echo "Checking PHP Lint..."
+for FILE in $SFILES
 do
-    if [[ "$var" = "M" ]] || [[ "$var" = "A" ]] || [[ "$var" = "D" ]]; then
-        continue
+    php -l -d display_errors=0 $PROJECT/$FILE
+    if [ $? != 0 ]
+    then
+        echo "Fix the error before commit."
+        exit 1
     fi
-
-    # check php file
-    if [[ ! ${var} =~ ".php" ]]; then
-        echo "Check file $var: not php file, ignoring..."
-        continue
-    fi
-
-    # phplint
-    if [[ ${phplint} == "true" ]]; then
-        phplintResult=`${phplint_path} $var | grep error`
-        if [[ x"$phplintResult" != x ]]; then
-            echo "-------------------------------------"
-            echo "Git commit error, get phplint errors:"
-            ${phplint_path} ${var} | while read line
-            do
-                echo ${line}
-            done
-            askContinue
-            exit 1
-        else
-            echo "phplint file [$var] success !"
-        fi
-    fi
-
-    # phpcs
-    if [[ ${phpcs} == "true" ]]; then
-        phpcsResult=`${phpcs_path} -n --standard=psr2 ${var} | grep ERROR | grep -v "0 ERRORS\|exist\|usage"`
-        if [[ x"$phpcsResult" != x ]]; then
-            echo "-------------------------------------"
-            echo "Git commit error, get phpcs errors:"
-            ${phpcs_path} -n --standard=psr2 ${var} | while read line
-            do
-                echo ${line}
-            done
-            askContinue
-            exit 1
-        else
-            echo "phpcs file [$var] success !"
-        fi
-    fi
+    FILES="$FILES $PROJECT/$FILE"
 done
 
-echo "Congratulations! Code check success!"
-exit 0
+if [ "$FILES" != "" ]
+then
+    echo "Running Code Sniffer. Code standard PSR2."
+    ./vendor/bin/phpcs --standard=PSR12 --colors --encoding=utf-8 -n -p $FILES
+    if [ $? != 0 ]
+    then
+        echo "Fix the error before commit!"
+        echo "Run"
+        echo "  ./vendor/bin/phpcs --standard=PSR2 $FILES"
+        echo "for automatic fix or fix it manually."
+        exit 1
+    fi
+fi
+
+exit $?
